# Generated by Django 5.1.7 on 2025-04-12 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JSKLegalInsightsapp', '0001_initial'),
    ]

    operations = [
    ]
