# Generated by Django 4.1.13 on 2025-04-20 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JSKLegalInsightsapp', '0003_casestudy_author'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['email', 'location'], name='JSKLegalIns_email_826651_idx'),
        ),
    ]
